In [1]:
import pandas as pd

In [4]:
df_temp=pd.read_csv('/Users/lambardaar/Downloads/skill-practice-lab/NLP/datasets/got_data/IMDB Dataset.csv')
df=df_temp.iloc[:10000]
df.shape

(10000, 2)

In [5]:
df.head(2)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive

In [10]:
df.duplicated().sum()

0

In [9]:
df.drop_duplicates(inplace=True)

/var/folders/2c/cq9fl3r13k327hnpyh8w9j0c0000gn/T/ipykernel_75823/3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [12]:
import re
def remove_html(text):
    clean_text=re.sub(re.compile('<.*?>'),' ',text)
    return clean_text

df['review']=df['review'].apply(remove_html)

/var/folders/2c/cq9fl3r13k327hnpyh8w9j0c0000gn/T/ipykernel_75823/2067095627.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(remove_html)

In [13]:
df['review']=df['review'].apply(lambda x:x.lower())

/var/folders/2c/cq9fl3r13k327hnpyh8w9j0c0000gn/T/ipykernel_75823/2697927567.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(lambda x:x.lower())

In [14]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    new_text = []

    for word in text.split():
        if word not in stop_words:
            new_text.append(word)

    return " ".join(new_text)

df['review']=df['review'].apply(remove_stopwords)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/lambardaar/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
/var/folders/2c/cq9fl3r13k327hnpyh8w9j0c0000gn/T/ipykernel_75823/3724187598.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(remove_stopwords)

In [15]:
df['review']

0       one reviewers mentioned watching 1 oz episode ...
1       wonderful little production. filming technique...
2       thought wonderful way spend time hot summer we...
3       basically there's family little boy (jake) thi...
4       petter mattei's "love time money" visually stu...
                              ...
9995    fun, entertaining movie wwii german spy (julie...
9996    give break. anyone say "good hockey movie"? kn...
9997    movie bad movie. watching endless series bad h...
9998    movie probably made entertain middle school, e...
9999    smashing film film-making. shows intense stran...
Name: review, Length: 9983, dtype: object

In [16]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['sentiment']=le.fit_transform(df['sentiment'])
df

/var/folders/2c/cq9fl3r13k327hnpyh8w9j0c0000gn/T/ipykernel_75823/3438655966.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sentiment']=le.fit_transform(df['sentiment'])

                                                 review  sentiment
0     one reviewers mentioned watching 1 oz episode ...          1
1     wonderful little production. filming technique...          1
2     thought wonderful way spend time hot summer we...          1
3     basically there's family little boy (jake) thi...          0
4     petter mattei's "love time money" visually stu...          1
...                                                 ...        ...
9995  fun, entertaining movie wwii german spy (julie...          1
9996  give break. anyone say "good hockey movie"? kn...          0
9997  movie bad movie. watching endless series bad h...          0
9998  movie probably made entertain middle school, e...          0
9999  smashing film film-making. shows intense stran...          1

[9983 rows x 2 columns]

In [23]:
x=df['review']
y=df['sentiment']
from sklearn. model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score

cv=CountVectorizer()
x_train_bow=cv.fit_transform(X_train).toarray()
x_test_bow=cv.transform(X_test).toarray()

from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()

gnb.fit(x_train_bow,y_train)
y_pred=gnb.predict(x_test_bow)
print(accuracy_score(y_test,y_pred))

0.6314471707561342

In [28]:
from sklearn. ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train_bow,y_train)
y_pred = rf. predict (x_test_bow)
accuracy_score(y_test,y_pred)

0.8482724086129194

In [33]:
cv = CountVectorizer (max_features=3000)
x_train_bow = cv. fit_transform(X_train). toarray ( )
x_test_bow = cv.transform(X_test) .toarray ()
rf = RandomForestClassifier()
rf.fit(x_train_bow,y_train)
y_pred = rf. predict (x_test_bow)
accuracy_score(y_test,y_pred)

0.8347521281922884

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()
rf = RandomForestClassifier()
rf.fit(X_train_tfidf, y_train)
y_pred = rf.predict(X_test_tfidf)
accuracy_score(y_test, y_pred)

0.8452679018527791