In [10]:
import pandas as pd 
df=pd.read_csv("/Users/lambardaar/Documents/study_hub/python/ml/naive_bayes/titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [11]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head(4)

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Sex']=le.fit_transform(df['Sex'])
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Fare'].fillna(df['Fare'].mean(), inplace=True)

/var/folders/2c/cq9fl3r13k327hnpyh8w9j0c0000gn/T/ipykernel_34707/947124768.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)
/var/folders/2c/cq9fl3r13k327hnpyh8w9j0c0000gn/T/ipykernel_34707/947124768.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Fare'].fillna(df['Fare'].mean(), inplace=True)

In [18]:
print(df.head())
target=df['Survived']
inputs=df.drop('Survived',axis=1)

   Survived  Pclass  Sex   Age     Fare
0         0       3    1  34.5   7.8292
1         1       3    0  47.0   7.0000
2         0       2    1  62.0   9.6875
3         0       3    1  27.0   8.6625
4         1       3    0  22.0  12.2875

In [13]:
inputs.Age.isnull().value_counts()

Age
False    418
Name: count, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.3 ,random_state=42)
X_train.isna().sum()

Pclass    0
Sex       0
Age       0
Fare      0
dtype: int64

In [22]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(X_train,y_train)
pred=model.predict(X_test)

TypeError: _BaseNB.predict() takes 2 positional arguments but 5 were given

In [16]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

1.0

In [19]:
df.head()

   Survived  Pclass  Sex   Age     Fare
0         0       3    1  34.5   7.8292
1         1       3    0  47.0   7.0000
2         0       2    1  62.0   9.6875
3         0       3    1  27.0   8.6625
4         1       3    0  22.0  12.2875

In [20]:
def pre(pclass, sex, age, fare):
    # Encode 'Sex' value
 
    # Prepare input DataFrame
    input_df = pd.DataFrame({
        'Pclass': [pclass],
        'Sex': [sex],
        'Age': [age],
        'Fare': [fare]
    })
    # Fit model on the full dataset
    X = df.drop('Survived', axis=1)
    y = df['Survived']
    model = GaussianNB()
    model.fit(X, y)
    # Predict for the input
    prediction = model.predict(input_df)
    return prediction[0]

In [21]:
pre(4,1,20,5.609)

1